In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

project_path = "/content/drive/MyDrive/Water_AI_Hackathon"
os.chdir(project_path)

print(os.getcwd())

/content/drive/MyDrive/Water_AI_Hackathon

In [ ]:
import pandas as pd

df = pd.read_csv("datasets/scarcity.csv")

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df.head()

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%),Water Scarcity Level
0,Argentina,2000,481.490000,235.431429,48.550000,20.844286,30.100000,1288.698571,3.255714,Moderate
1,Argentina,2001,455.063000,299.551000,48.465000,26.943000,22.550000,1371.729000,3.120000,Moderate
2,Argentina,2002,482.749231,340.124615,50.375385,29.042308,23.349231,1590.305385,2.733846,Moderate
3,Argentina,2003,452.660000,326.756667,49.086667,30.476000,24.440000,1816.012667,2.708000,Moderate
4,Argentina,2004,634.566000,230.346000,38.670000,36.670000,23.924000,815.998000,1.902000,Moderate

In [ ]:
df.tail()

,Country,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%),Water Scarcity Level
495,USA,2020,418.097,292.9700,47.448,25.2660,27.5380,1510.662,2.4310,Moderate
496,USA,2021,572.094,275.9780,46.195,32.2230,26.7200,754.615,2.6280,Moderate
497,USA,2022,440.978,292.0390,54.810,30.9180,22.6380,2119.898,2.8710,Moderate
498,USA,2023,566.865,261.1975,62.945,25.2075,21.6325,1439.155,1.5975,Moderate
499,USA,2024,249.485,186.3740,51.386,24.7690,27.6770,1771.199,1.6380,High

In [ ]:
df.shape

(500, 10)

In [ ]:
df.columns

Index(['Country', 'Year', 'Total Water Consumption (Billion Cubic Meters)',
       'Per Capita Water Use (Liters per Day)', 'Agricultural Water Use (%)',
       'Industrial Water Use (%)', 'Household Water Use (%)',
       'Rainfall Impact (Annual Precipitation in mm)',
       'Groundwater Depletion Rate (%)', 'Water Scarcity Level'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Country                                         500 non-null    object
 1   Year                                            500 non-null    int64
 2   Total Water Consumption (Billion Cubic Meters)  500 non-null    float64
 3   Per Capita Water Use (Liters per Day)           500 non-null    float64
 4   Agricultural Water Use (%)                      500 non-null    float64
 5   Industrial Water Use (%)                        500 non-null    float64
 6   Household Water Use (%)                         500 non-null    float64
 7   Rainfall Impact (Annual Precipitation in mm)    500 non-null    float64
 8   Groundwater Depletion Rate (%)                  500 non-null    float64
 9   Water Scarcity Level                            500 non-null    object
dtypes: float64(7), int64(1), object(2)
memory usage: 39.2+ KB

In [ ]:
df.describe()

,Year,Total Water Consumption (Billion Cubic Meters),Per Capita Water Use (Liters per Day),Agricultural Water Use (%),Industrial Water Use (%),Household Water Use (%),Rainfall Impact (Annual Precipitation in mm),Groundwater Depletion Rate (%)
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,2012.000000,501.224430,276.004782,50.180829,27.792837,24.832515,1544.824300,2.573037
std,7.218324,96.078937,42.669593,5.566886,4.361660,2.956135,292.786579,0.480630
min,2000.000000,129.636667,111.708333,28.905000,13.276667,13.668333,700.230000,1.300000
25%,2006.000000,441.447385,250.225406,46.513611,25.018000,23.015355,1353.734583,2.235000
50%,2012.000000,502.197154,276.430556,50.318482,27.648539,25.071944,1537.537724,2.555778
75%,2018.000000,563.849594,300.221750,54.061964,30.698333,26.720167,1746.402425,2.887202
max,2024.000000,798.418000,404.350000,66.520000,43.583333,34.202000,2533.678000,4.322000

In [ ]:
df.isnull().sum()

Country                                           0
Year                                              0
Total Water Consumption (Billion Cubic Meters)    0
Per Capita Water Use (Liters per Day)             0
Agricultural Water Use (%)                        0
Industrial Water Use (%)                          0
Household Water Use (%)                           0
Rainfall Impact (Annual Precipitation in mm)      0
Groundwater Depletion Rate (%)                    0
Water Scarcity Level                              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Water Scarcity Level"].value_counts()

Water Scarcity Level
Moderate    360
Low         122
High         18
Name: count, dtype: int64

In [ ]:
df["Country"].value_counts()

Country
Argentina       25
Australia       25
Brazil          25
Canada          25
China           25
France          25
Germany         25
India           25
Indonesia       25
Italy           25
Japan           25
Mexico          25
Russia          25
Saudi Arabia    25
South Africa    25
South Korea     25
Spain           25
Turkey          25
UK              25
USA             25
Name: count, dtype: int64

In [ ]:
df.to_csv("/content/drive/MyDrive/Water_AI_Hackathon/outputs/scarcity_cleaned.csv", index=False)